#!/bin/bash

#$1 = '$file_name'
#$2 = '$file_base_name'

##################A projekt paraméterei:################
fordito="javac"
projectfileok="*.java"
parameterek=""
futtato="java"
nev="Main"
futtatas=true
########################################################



################Fordítás és futtatás:###################
if [[ ! -d "bin" ]]; then
	mkdir "bin"
fi

$fordito -d bin $parameterek $projectfileok

if [[ "$futtatas" = true ]]; then
	$futtato -cp bin $nev
fi
########################################################